config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do 
  end

  get 'get_exchange_values/(:id)', to:  'products#get_exchange_values'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/price_list.rb
class PriceList < ActiveRecord::Base
	serialize :prices, Hash
end

app/models/product.rb
class Product < ActiveRecord::Base
 require 'httpclient'
 require 'active_support/core_ext'


  def price
    price_in_cents / 100.0
  end

  def self.get_currency_rate(status,prod)
    price_list = PriceList.last
    base_value = prod.price_in_cents/100.0

    if (price_list.blank? || (!price_list.blank? && price_list.published_date < Date.today))
      res = HTTPClient.get("https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml")
      hash = Hash.from_xml(res.body)["Envelope"]["Cube"]["Cube"][0]
      price_list = PriceList.create({:prices => hash , published_date: Time.now.to_date})
    end
    a =  price_list.prices["Cube"].select{|k,v| k["currency"] == status}[0].values[1]
    result = "%0.2f" % [a.to_f * base_value]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @currency = Currency.all
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def get_exchange_values

    unless params[:id].blank?
      product = Product.find_by(:id => params[:id])
      render json: [] if product.blank?

      @current_value = {:id => product.id , :currency => get_currency_rate(params["currency"],product)}

      render json: [@current_value.compact]

    else
      
      @current_values = Product.all.collect{|product| {:id => product.id , :currency => Product.get_currency_rate(params["currency"],product)} }
      render json: @current_values.compact
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head>
  %title 3scale marketplace
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  %main.container
    
    = yield
  %footer.footer
    %div.footer_content
      %div{:style => "padding: 2rem;"}
        %p @2015 by you
      %div{:style => "padding: 2rem;"}
        = select_tag "Change Currency", options_for_select([ "USD", "JPY", "EUR" ], "EUR")
     

app/views/products/index.html.erb
<h1>Check out our products!</h1>

<div class="row product-list">
  <% @products.each do |product| %>
     <article class="product"  data-prod = <%= product.id%>>
      <h2>
        <%= product.name %>
      </h2>
      <p>
        <%= product.description %>
      </p>
      <strong>
       <div class="text-data"  id="prod_cur_<%= product.id%>"> <%= product.price %>&nbsp;<label>EUR</label>
        &nbsp;&nbsp;&nbsp;
        <%= link_to 'Show more', product %>
      </strong>
    </article>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row product-list">
  <article class="product"  data-prod = <%= @product.id%>>
    <h2>
      <%= @product.name %>
    </h2>
    <p>
      <%= @product.description %>
    </p>
   
    <div class="text-data"  id="prod_cur_<%= @product.id%>"> <strong> <%= @product.price %>&nbsp;<label>EUR</label>
       <%= link_to 'back to product list', products_path %>
      </strong>
    </div>
  </article>
</div>